// params_list.h  (the only place you list params)
X_FLOAT(gain, 0.0)
X_INT(gyro_avg, 0)
X_FLOAT(steering_prio, 0.0)
X_INT(debug_serial, 0)
X_FLOAT(correction_exp, 1.0)
X_INT(gyro_lp_hz, 20)
X_INT(derivative_lp_hz, 20)
X_INT(steer_in_lp_hz, 20)
X_INT(steer_out_lp_hz, 20)
X_FLOAT(pid_p, 5.0)
X_FLOAT(pid_d, 1.0)
X_FLOAT(wobble_det_a, 0.2)
X_FLOAT(dd_min_steer,0.05)
X_FLOAT(dd_min_yaw,10)
X_FLOAT(dd_multiplier,1)
X_FLOAT(max_d_corr,0.05)
